#!/bin/bash
start()
{
    echo "start mail-deliver"
    cd /home/gengs/develops/emailDeliver
    /home/gengs/develops/emailDeliver/mail-deliver.pl >> /tmp/mail-deliver.log &
    exit 0;
}
stop()
{
     pkill mail-deliver.pl
     echo "stop mail-deliver"
}

case "$1" in
start)
    start
    ;;
stop)
    stop
    ;;
restart)
    stop
    start
    ;;
*)
    echo "usage: $0 start|stop|restart"
    exit 0;
esac