#!/bin/bash
start()
{
    echo "start mail-deliver"
    /usr/local/bin/mail-deliver.pl >> /var/log/mail-deliver/mail-deliver.log &
    exit 0;
}
stop()
{
     pkill mail-deliver.pl
     echo "stop mail-deliver"
}

case "$1" in
start)
    start
    ;;
stop)
    stop
    ;;
restart)
    stop
    start
    ;;
*)
    echo "usage: $0 start|stop|restart"
    exit 0;
esac